### PR TITLE
Making the back button work - #249

### PR DESCRIPTION
**Pull request by larryprice**
Filling in popstate call and manipulating page to represent desired state after hitting the Back/Forward buttons. Addresses #249

### CODE REVIEW

**Comment by jdm** [comment]
Thanks! I'm on vacation right now and so I'm unsure precisely when I'll be able to review these changes, but please remind me here if I have not merged this by June 30!

**Comment by larryprice** [comment]
@jdm thanks for letting me know - I've grown all too used to waiting in silence for weeks before maintainers respond.

**Comment by larryprice** [comment]
ping @jdm

**Comment by jdm** [comment]
Thanks! These changes make sense after paging all this code back into my brain :)

**Pull request merged**
