### PR TITLE
Nepali Locale Initiated

### PR DESCRIPTION
**Pull request by Avasz**
Initiated Nepali Locale. 
Translated around 40% of strings.

### CODE REVIEW

**Comment by Avasz** [comment]
Please accept the pull request for Nepali locale.
Next pull request after all strings have been localized.
Please let me know if anything needs else is required to be done. 
Thanks

**Comment by jdm** [comment]
The only change missing is adding an entry to the `<select>` in index.html. I'll be happy to merge with that change included :)

**Comment by Avasz** [comment]
Hello, I have added ne-NP in <select>.
Please accept it.
A little bit busy right now so haven't finished completing it, but still, should be good as an initiation. :)

Thanks.

**Comment by jdm** [comment]
Thank you!

**Pull request merged**
