### PR TITLE
Interactive and Reachable

### PR DESCRIPTION
**Pull request by abhi4mu**
Added address content for every page.

There is an unreachable code from "Writing Code/C++/Gecko", resolved it.

### CODE REVIEW

**Comment by jdm** [comment]
Sorry for forgetting about this! @abhi4mu Could you take a couple screenshots that show what your changes look like?

**Comment by abhi4mu** [comment]
Annotation 2020-08-01 133657

**Comment by abhi4mu** [comment]
You can see that there are sub modules in gecko. These modules are present in the previous code itself, but it is unreachable, now I recovered that.

**Comment by abhi4mu** [comment]
Could you please look after this jdm, Thanks!

**Comment by jdm** [comment]
I'm not sure I understand the goal here. Why do we want to add these extra links?

**Comment by abhi4mu** [comment]
when I first visited this site I found it difficult to know in which section I'm in or did I already visited this page etc.
If we provide them with these they will get an idea in which section they are and in that way one will be clear once and for all.

**Comment by jdm** [comment]
I'm not actively working on this site any more, and I'm not convinced that these changes are a good fit. Sorry for leaving this PR alone for so long!

**Pull request closed without merging**
