### PR TITLE
Fix issue #313: Get new mozilla logo + update style to match mozilla.…

### PR DESCRIPTION
**Pull request by pascalchevrel**
…org a bit more

* svg version of the logo
* Added Fira fonts to the site to replace call to remote OpenSans
* Moved all assets to sub-folders in /media/css /media/fonts /media/js /media/img
* Removed dead CSS in style.css
* Removed all tabzilla files and references

### CODE REVIEW

**Comment by jdm** [comment]
Judging by the screenshot in #313, I'm not thrilled about the dark menu at the top of the page. The current design's logo and menu are discreet and do not distract; I feel that the sharp contrast from the dark menu draws too much attention to it.

**Comment by pascalchevrel** [comment]
How about this?
https://tests.pascalc.net/asknot/

**Comment by hkoivuneva** [comment]
Looks great! I like it! I'll try to find time to create new button styles etc. so we can get it even closer to 2017!23.1.2017 9.58 ip. Pascal Chevrel <notifications@github.com> kirjoitti:How about this?
https://tests.pascalc.net/asknot/

**Comment by pascalchevrel** [comment]
I asked the design team on their mailing list and we can only use a black background for the logo so I updated my PR with that color.

**Comment by jdm** [comment]
Thanks! Sorry about the delay!

**Comment by pascalchevrel** [comment]
Thanks! Unrelated to this PR but the site got promoted by an influential French tech blogger today :) https://korben.info/pouvez-faire-mozilla.html

**Pull request merged**
