### PR TITLE
Workflow Improvements

### PR DESCRIPTION
**Pull request by SamuelMoraesF**
Modifications made by @joridos, the same PR of [@mozillabrasil/participe#1](https://github.com/mozillabrasil/participe/pull/1).

**en-EN version:**

Added the grunt and some tasks to improve Workflow.

Before:

687474703a2f2f692e696d6775722e636f6d2f4855444154556c2e706e67

Now:

687474703a2f2f692e696d6775722e636f6d2f355672397333652e706e67

All credits to @joridos

[Review on Reviewable](https://reviewable.io/reviews/jdm/asknot/255)

### CODE REVIEW

**Comment by jdm** [comment]
Thank you for contributing these change! However, one of the advantages of the current code is that only a python installation is required, which is much less effort than setting up node.js in my experience. I would be interested in a separate PR that only includes the changes reflected in the screenshots; I'm not interested in merging all of the file moves and node infrastructure changes.

**Comment by joridos** [comment]
:+1: Ok

**Comment by SamuelMoraesF** [comment]
@joridos, can you make a new PR?

**Comment by joridos** [comment]
@SamuelMoraesF I'm not have much time to do it now, but if you can do for me I really appreciate that.

**Comment by SamuelMoraesF** [comment]
@joridos, I added to my todo list.

After I get this done, I'll open a new PR.

Thanks!

**Pull request closed without merging**
